name: rebus
favicon: null
layout_spectrum: 0.7541364482603967
typography_spectrum: 0.11747182602994144
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.05019017308950424
  lightness: 0.8887480420526117
  saturation: 0.8681749384850264
  rhythmicContrast: 0.242552186595276
purpose: []
